### PR TITLE
Add config class

### PR DESCRIPTION
**Pull request by phillbaker**
Redo of https://github.com/akxcv/vuera/pull/90. ea55634 fixes the build bug in https://github.com/akxcv/vuera/pull/90#issuecomment-529439080 - sorry about that!

Also closes https://github.com/akxcv/vuera/pull/83

### CODE REVIEW

**Comment by phillbaker** [comment]
@akxcv any thoughts here? Happy to investigate the failing tests if this makes sense.

**Comment by phillbaker** [comment]
cc @fanyer since it seems like you're helping out on this repo now (based on #97 )

**Comment by timsayshey** [comment]
@phillbaker Is this pull-request dead?

**Comment by phillbaker** [comment]
Was waiting on a review/merge. But seems like it would still be useful and
relevant.

**Comment by akxcv** [comment]
Hey, I thought I commented on this, but apparently not. I thought that making config a JS class would be more readable/maintainable, but an object will do for now. Could you please describe in a few words how to actually use this feature in code? Could you provide a minimal sample?

**Comment by phillbaker** [comment]
Thanks @akxcv for taking another look.

> Could you please describe in a few words how to actually use this feature in code? 

The key problem this is solving is that instance options set at the top level `Vue` instances are not passed down to Vue instances within react components. So, for example an `i18n` instance option configured at the top level is not available in the children Vue components wrapped in React components.

> Could you provide a minimal sample?

Sure - very similar to the example, in https://github.com/akxcv/vuera/pull/83#issue-283419857:
```
import Vue from "vue";
import { config } from "vuera";
import VueI18n from "vue-i18n";
import React from "react";
import { render } from "react-dom";
import { VsTable } from "example-vue-component-library";

Vue.use(VueI18n);
const i18n = new VueI18n({
  locale: "en",
  messages: {
    en: {
      no_data: "No data"
    }
  }
});

config.vueInstanceOptions = { i18n };

render(
  <div>
    <VsTable data={[]} />
  </div>,
  document.querySelector("#app")
);
```

**Comment by akxcv** [comment]
Yeah, this will work for now. Could you please describe this functionality in the README? Then we can merge this.

**Comment by phillbaker** [comment]
Done!

**Pull request merged**
