### PR TITLE
Add config class & Vue instance options

### PR DESCRIPTION
**Pull request by phillbaker**
This builds off of https://github.com/akxcv/vuera/pull/83 by adding a config object for the options. As well, it adds tests for the usage. 

@akxcv I didn't update the `dist/` files, but I can do that if this looks good.

Would close https://github.com/akxcv/vuera/issues/82.

### CODE REVIEW

**Comment by phillbaker** [comment]
@akxcv did you get a chance to look at this? Any thoughts?

**Comment by akxcv** [comment]
Hi! Yes, I did take a look at your code, but I'll carve out a bit more time to write up a review.

BTW, `dist/` is updated automatically via pre-commit hooks!

**Comment by akxcv** [comment]
Sorry, I'm having trouble with finding time for the review. I guess I'll merge this as is because the code seems to work.

**Comment by akxcv** [comment]
@phillbaker unfortunately, I had to revert this, because `yarn build` does not work because of some broken exports, apparently.

**Comment by phillbaker** [comment]
Sorry to hear that - can you post a stack trace and I’ll take a look?

**Comment by akxcv** [comment]
<details>
  <summary>`yarn build` output</summary>

```bash
$ yarn build
yarn run v1.12.3
$ cross-env BABEL_ENV=rollup rollup -c

src/index.js → dist/vuera.cjs.js...
[!] Error: 'setVueInstanceOptions' is not exported by src/wrappers/Vue.js
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
src/index.js (2:21)
1: import ReactWrapper from './wrappers/React';
2: import VueWrapper, { setVueInstanceOptions } from './wrappers/Vue';
                        ^
3: import VuePlugin from './VuePlugin';
4: import VueInReact, { babelReactResolver as __vueraReactResolver } from './resolvers/React';

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

</details>

**Comment by phillbaker** [comment]
Ah, I think it was the issue that dist/ was updated.

**Pull request merged**
